### PR TITLE
Support testing MicroProfile Fault Tolerance 4.1 

### LINKED ISSUE #309: Support MP Fault tolerance 4.1
To allow executing tests against WildFly version that will integrate MicroProfile 7.0 specs.

### PR DESCRIPTION
**Pull request by fabiobrz**
MicroProfile 7.0 provides MicroProfile Fault Tolerance 4.1, and the test suite should support such version, see https://issues.redhat.com/browse/WFLY-19588, https://issues.redhat.com/browse/WFLY-19592, https://issues.redhat.com/browse/WFLY-19590

- [A dedicated module has been created](https://github.com/fabiobrz/eap-microprofile-test-suite/tree/issues-309.mp-ft-41x/tooling-observability) to provide Observability tooling to other modules, namely by `microprofile-fault-tolerance` for this PR, and the `micrometer` module is refactored accordingly
- The `UndeployDeployTest::testFaultToleranceMeticsAreTracedWithSameDeployments`, which was dropped in #276 is restored to work with MP Telemetry generated metrics and test MP Fault Tolerance -> MP Telemetry integration.

Fixes #309 

---
Please make sure your PR meets the following requirements:
- [x] Pull Request contains a description of the changes
- [x] Pull Request does not include fixes for multiple issues/topics
- [x] Code is formatted, imports ordered, code compiles and tests are passing
- [x] Link to the passing job is provided
- [x] Code is self-descriptive and/or documented
- [x] Description of the tests scenarios is included (see #46)

### CODE REVIEW

**Comment by marekkopecky** [comment]
@fabiobrz It seems that there are some CI failures:

```
2024-11-11T14:34:21.6599015Z [ERROR] Errors: 
2024-11-11T14:34:21.6607510Z [ERROR]   DatabaseCrashTest.startDatabase:128 » Docker postgres-deeb464c-1fdd-4884-ae6e-983f354d3e51 - Starting of docker container using command: "docker run --name postgres-deeb464c-1fdd-4884-ae6e-983f354d3e51 -p 5432:5432 -e POSTGRESQL_PASSWORD=pass -e POSTGRESQL_DATABASE=test-database -e POSTGRESQL_USER=user -v /home/runner/work/eap-microprofile-test-suite/eap-microprofile-test-suite/microprofile-fault-tolerance/target/8064438419830345556:/var/lib/pgsql/data:Z quay.io/centos7/postgresql-13-centos7:centos7" failed. Check that provided command is correct.
2024-11-11T14:34:21.6612525Z [ERROR]   UndeployDeployTest.testFaultToleranceMetricsAreTracedWithSameDeployments:157 » ArrayIndexOutOfBounds Index 1 out of bounds for length 1
```

Can you please double-check? Btw, which WF branch is the CI running against? Maybe we are rather interested in mp-7-wip branch?

**Comment by marekkopecky** [comment]
Thank you for the PR. The code changes LGTM, I would just like to check CI.

**Comment by fabiobrz** [comment]
> Ah, and the answer seems to be in #312
> 
> Do you already have some link to CI for this PR?

In order to have it we should merge #312 first, but the new test in this PR passed internally: see e.: **job**: eap-8.x-microprofile-testsuite, **run nr.** 1124.

**Review by marekkopecky — APPROVED** [review]
Thank you! Reference for 1124 run is good enough for me. Merging.

**Pull request merged**
