### PR TITLE
Remove unused tooling-server-utilities

### PR DESCRIPTION
**Pull request by mnovak1**
Link to Jenkins run:
https://eap-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/eap-7.x-microprofile-testsuite/88/

Please make sure your PR meets the following requirements:
- [x] Pull Request contains a description of the changes
- [x] Pull Request does not include fixes for multiple issues/topics
- [x] Code is formatted, imports ordered, code compiles and tests are passing
- [x] Link to the passing job is provided
- [x] Code is self-descriptive and/or documented
- [x] Description of the tests scenarios is included (see #46)

### CODE REVIEW

**Comment by fabiobrz** [comment]
Hi @mnovak1, I can run a successful build on your branch and `Waiter` is actually never used. So basically this one would seem good to go. I am wondering whether this was intended to be used in future? WDYT?

P.S. Travis CI build overall status looks pending but both builds are actually succeeding.

**Comment by mnovak1** [comment]
@fabiobrz There is http://www.awaitility.org/ which is basically replacing it.

**Comment by fabiobrz** [comment]
> @fabiobrz There is http://www.awaitility.org/ which is basically replacing it.

Thanks @mnovak1, this LGTM then, approving.

**Comment by mnovak1** [comment]
@fabiobrz great, thanks

**Comment by honza-kasik** [comment]
LGTM! Thanks! Merging!

**Pull request merged**
