### PR TITLE
Jenkinsfile to compile WildFly and run the TS

### PR DESCRIPTION
**Pull request by rsvoboda**
Jenkinsfile to compile WildFly and run the TS

Enables custom repository and branch definition for both WildFly and test-suite.

Please make sure your PR meets the following requirements:
- [x] Pull Request contains description for the changes
- [x] Pull Request does not include fixes for multiple issues / topics
- [x] Code compiles and tests are passing
- [x] Code is self-descriptive and/or documented
- [x] Description of the tests scenarios is included (see #46)

Note: First run will fail due to https://issues.jenkins-ci.org/browse/JENKINS-40574 / https://issues.jenkins-ci.org/browse/JENKINS-41929 but all the subsequent runs will work

### CODE REVIEW

**Comment by rsvoboda** [comment]
Screenshots from Jenkins:
Screenshot 2019-11-28 at 10 39 10
Screenshot 2019-11-28 at 10 39 42

**Comment by mnovak1** [comment]
@rsvoboda could you provide some context to Jenkinsfile usage, please? I'm missing following information:
- In which Jenkins version/url it's supposed to be run
- Jenkins Plugins needed to be installed
- Expectations from the Jenkins slaves - like installed OS, JDK, Maven
- Expected labels for slaves and JDK

**Comment by rsvoboda** [comment]
Main requirement is Pipeline plugin - https://plugins.jenkins.io/workflow-aggregator, Jenkins version requirement is defined by this plugin.

Requirements for tools/labels are defined in Jenkinsfile itself
```ruby
    agent { label 'linux' }
    tools {
        jdk 'java-1.8.0-oracle'
    }
```

**Comment by rsvoboda** [comment]
merging as agreed here - https://github.com/jboss-eap-qe/eap-microprofile-test-suite/issues/69#issuecomment-562140115

**Pull request merged**
