### PR TITLE
Copy jboss as to target and use jboss.dist

### PR DESCRIPTION
**Pull request by istraka**
Fixes https://github.com/jboss-eap-qe/eap-microprofile-test-suite/issues/129

tests pass

run with `-Djboss.dist`
```
[INFO] Test suite for MicroProfile on WF/EAP .............. SUCCESS [  1.434 s]
[INFO] tooling-server-configuration ....................... SUCCESS [ 12.922 s]
[INFO] microprofile-health ................................ SUCCESS [ 36.988 s]
[INFO] microprofile-metrics ............................... SUCCESS [ 27.071 s]
[INFO] server-utilities ................................... SUCCESS [  3.200 s]
[INFO] microprofile-jwt-auth-tool ......................... SUCCESS [  0.235 s]
```

run without `-Djboss.dist` - WildFly is downloaded
```
[INFO] Test suite for MicroProfile on WF/EAP .............. SUCCESS [  3.801 s]
[INFO] tooling-server-configuration ....................... SUCCESS [ 12.562 s]
```
Other modules expect newer wildfly than defined in profile downloading WildFly

Please make sure your PR meets the following requirements:
- [x] Pull Request contains a description of the changes
- [x] Pull Request does not include fixes for multiple issues/topics
- [x] Code is formatted, imports ordered, code compiles and tests are passing
- [ ] Link to the passing job is provided
- [x] Code is self-descriptive and/or documented
- [x] Description of the tests scenarios is included (see #46)

### CODE REVIEW

**Comment by istraka** [comment]
Follow-up MR: https://gitlab.mw.lab.eng.bos.redhat.com/jbossqe-eap/tests-jobs/merge_requests/1197

**Comment by zhantemirov** [comment]
I read the discussion https://github.com/jboss-eap-qe/eap-microprofile-test-suite/issues/129 and the changes presented here looks good to me. 

@istraka does these changes need to be reflected somehow in README.md? I mean https://github.com/jboss-eap-qe/eap-microprofile-test-suite#quick-compilation-of-the-code part.

**Comment by mnovak1** [comment]
Yes, readme should be updated as well but as @istraka is on PTO I will do it in separate PR.

**Comment by mnovak1** [comment]
Looks like this should be also change in `.travis.yml`

**Comment by istraka** [comment]
Fixed

**Comment by honza-kasik** [comment]
Thanks - LGTM, merging...

**Pull request merged**
