### PR TITLE
Fixes #101 - commons-io replaced with standard Java API

### LINKED ISSUE #101: Replace commons-io dependency with standard Java API
Replace commons-io dependency with standard Java API

It's used mainly for reading and writing content from / to files.

`java.nio.file.Files` is sufficient replacement with similar API.
`java.nio.file.Files` is Java 7+ API.

### PR DESCRIPTION
**Pull request by rsvoboda**
Fixes #101 - commons-io replaced with standard Java API

Please make sure your PR meets the following requirements:
- [x] Pull Request contains description for the changes
- [x] Pull Request does not include fixes for multiple issues / topics
- [x] Code is formatted, imports ordered, code compiles and tests are passing
- N/A Link to passing job is provided
- [x] Code is self-descriptive and/or documented
- N/A Description of the tests scenarios is included (see #46)

### CODE REVIEW

**Comment by rsvoboda** [comment]
No link to the job as I'm not on VPN, code compiles - see Travis check, no changes to test coverage.

**Comment by honza-kasik** [comment]
@rsvoboda Are metrics tests still passing?

**Comment by rsvoboda** [comment]
Yes - [WARNING] Tests run: 35, Failures: 0, Errors: 0, Skipped: 2, same as without my changes.

**Comment by rsvoboda** [comment]
I will merge now.
We can have another PR (or revert) if there are additional comments or concerns.

**Pull request merged**
